### ISSUE TITLE
problem in applying the 'QT GUI DoA compass'

### ISSUE THREAD

**Issue by Sea-of-Silence** [EttusResearch/gr-doa#10]
## Issue Description ##

hello:

          When i simulate the gr-doa in gnuradio 3.7.13.4, i encountered an problem which may be related to the 'QT GUI DoA Compass' module.

           As follows:

Generating: '/home/cruise/mygnuradio/grc program/MUSIC_simulation.py'

Executing: /usr/bin/python2 -u /home/cruise/mygnuradio/grc program/MUSIC_simulation.py

Traceback (most recent call last):
  File "/home/cruise/mygnuradio/grc program/MUSIC_simulation.py", line 193, in <module>
    main()
  File "/home/cruise/mygnuradio/grc program/MUSIC_simulation.py", line 181, in main
    tb = top_block_cls()
  File "/home/cruise/mygnuradio/grc program/MUSIC_simulation.py", line 77, in __init__
    self.top_grid_layout.addWidget(self.doa_qt_compass_0.this_layout)
TypeError: arguments did not match any overloaded call:
  addWidget(self, QWidget): argument 1 has unexpected type 'QVBoxLayout'
  addWidget(self, QWidget, int, int, alignment: Union[Qt.Alignment, Qt.AlignmentFlag] = 0): argument 1 has unexpected type 'QVBoxLayout'
  addWidget(self, QWidget, int, int, int, int, alignment: Union[Qt.Alignment, Qt.AlignmentFlag] = 0): argument 1 has unexpected type 'QVBoxLayout'

>>> Done (return code 1)

**Comment by yunerqing** [comment]
so did i,do you have solved this problem?

**Comment by crazylay** [comment]
I have solved this problems, this block  get something wrong ,you can use another block in grc --QT GUI number sink,the software offer it .

**Comment by jose100310** [comment]
What parameters did you use @crazylay for the QT GUI Number Sink? 

How does this block represents the data as?

Thank You,
Jose
